data:
  raw: data/raw
  processed: data/processed

training:
  random_seed: 42
  test_size: 0.2
  smote: true
  model:
    type: xgboost
    params:
        n_estimators: 200
        max_depth: 4
        learning_rate: 0.28569098318230135
        subsample: 0.7297540702680417
        colsample_bytree: 0.6003714313953341
